Repository MoimService/Moim-FE, pull requests merged in 2025-02, with the labels that each got.

#4 Feat/setting/codecov coderabbit/ DEVING-30
  .coderabbit.yml
  .husky/pre-commit
  package.json
Labels: 🔧 chore

#6 Feat/setting/tailwind-config/DEVING-14
  src/app/globals.css
  src/app/page.tsx
  tailwind.config.ts
Labels: 🔧 chore

#7 Feat/setting/folder structure/DEVING-27
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/test/components/TestComponent.tsx
  src/app/test/page.tsx
  src/assets/README.md
  src/assets/icon/favicon.ico
  src/components/README.md
  src/hooks/README.md
  src/lib/README.md
  src/service/README.md
  src/service/api/endpoints.ts
  src/store/README.md
  src/styles/README.md
  src/styles/globals.css
  src/types/README.md
  src/util/README.md
Labels: 🔧 chore, ⚙️ setting, 📝 docs, 🐛 fix

#8 Feat/setting/DEVING-8
  .coderabbit.yml
  .github/pull_request_template.md
  .github/workflows/pr-check.yml
  .github/workflows/pr-labeler.yml
  .husky/pre-commit
  .prettierrc
  __tests__/add.test.ts
  eslint.config.mjs
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  postcss.config.js
  postcss.config.mjs
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/test/components/TestComponent.tsx
  src/app/test/page.tsx
  src/assets/README.md
  src/assets/icon/favicon.ico
  src/components/README.md
  src/hooks/README.md
  src/lib/README.md
  src/service/README.md
  src/service/api/endpoints.ts
  src/store/README.md
  src/styles/README.md
  src/styles/globals.css
  src/types/README.md
  src/util/README.md
  src/util/add.ts
  tailwind.config.ts
  tsconfig.json
Labels: 🔧 chore, ⚙️ setting, 📝 docs, 🐛 fix

#9 Feat/components/general button/DEVING-32
  .prettierrc
  components.json
  eslint.config.mjs
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/preview/button/page.tsx
  src/components/ui/Button.tsx
  src/styles/globals.css
  src/util/cn.ts
  tailwind.config.ts
Labels: ✨ feat, 🔧 chore, 📝 docs

#10 Feat/component/floating button/DEVING-22
  src/app/preview/button/page.tsx
  src/components/ui/Button.tsx
  src/components/ui/FloatingButton.tsx
Labels: ✨ feat, 🐛 fix, ✅ test

#11 Feat/component/dropdown/DEVING-36
  .coderabbit.yaml
  package-lock.json
  package.json
  src/app/preview/dropdown/page.tsx
  src/components/common/Dropdown.tsx
  src/components/ui/Dropdown.tsx
Labels: ✨ feat, 🔧 chore, 📝 docs, 🐛 fix, 💄 style, AI Review, ♻️ refactor

#13 Feat/component/gnb/DEVING-15
  .coderabbit.yaml
  next.config.mjs
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/preview/dropdown/page.tsx
  src/app/preview/gnb/page.tsx
  src/assets/icon/logo.svg
  src/assets/icon/profile.svg
  src/components/common/Header.tsx
  src/fonts/PretendardVariable.woff2
  src/types/global.d.ts
  tailwind.config.ts
  tsconfig.json
Labels: ✨ feat, 🔧 chore, 🐛 fix

#15 Feat/component/input/DEVING-34 Input 컴포넌트 개발
  src/app/preview/input/page.tsx
  src/components/ui/Input.tsx
Labels: ✨ feat, 🔧 chore, 🐛 fix, 💄 style, AI Review, ♻️ refactor

#14 Feat/component/modal/DEVING-38
  src/app/preview/modal/Some.tsx
  src/app/preview/modal/page.tsx
  src/components/ui/modal/Modal.tsx
  tailwind.config.ts
Labels: ✨ feat, 🔧 chore, 🐛 fix, ✅ test, AI Review

#16 Feat/component/DEVING-9
  .coderabbit.yml
  .prettierrc
  components.json
  eslint.config.mjs
  next.config.mjs
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/preview/button/page.tsx
  src/app/preview/dropdown/page.tsx
  src/app/preview/gnb/page.tsx
  src/app/preview/input/page.tsx
  src/app/preview/modal/Some.tsx
  src/app/preview/modal/page.tsx
  src/assets/icon/logo.svg
  src/assets/icon/profile.svg
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/components/ui/Button.tsx
  src/components/ui/Dropdown.tsx
  src/components/ui/FloatingButton.tsx
  src/components/ui/Input.tsx
  src/components/ui/modal/Modal.tsx
  src/fonts/PretendardVariable.woff2
  src/styles/globals.css
  src/types/global.d.ts
  src/util/cn.ts
  tailwind.config.ts
  tsconfig.json
Labels: ✨ feat, 🔧 chore, 📝 docs, 🐛 fix, ✅ test, 💄 style, ♻️ refactor

#21 dev 브랜치 markup 에픽 동기화
  .github/pull_request_template.md
  .github/workflows/pr-check.yml
  .github/workflows/pr-labeler.yml
  .husky/pre-commit
  .prettierrc
  __tests__/add.test.ts
  components.json
  eslint.config.mjs
  jest.config.ts
  jest.setup.ts
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  postcss.config.mjs
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/preview/button/page.tsx
  src/app/preview/dropdown/page.tsx
  src/app/preview/gnb/page.tsx
  src/app/preview/input/page.tsx
  src/app/preview/modal/Some.tsx
  src/app/preview/modal/page.tsx
  src/app/test/components/TestComponent.tsx
  src/app/test/page.tsx
  src/assets/README.md
  src/assets/icon/favicon.ico
  src/assets/icon/logo.svg
  src/assets/icon/profile.svg
  src/components/README.md
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/components/ui/Button.tsx
  src/components/ui/Dropdown.tsx
  src/components/ui/FloatingButton.tsx
  src/components/ui/Input.tsx
  src/components/ui/modal/Modal.tsx
  src/fonts/PretendardVariable.woff2
  src/hooks/README.md
  src/lib/README.md
  src/service/README.md
  src/service/api/endpoints.ts
  src/store/README.md
  src/styles/README.md
  src/styles/globals.css
  src/types/README.md
  src/types/global.d.ts
  src/util/README.md
  src/util/add.ts
  src/util/cn.ts
  tailwind.config.ts
  tsconfig.json
Labels: 🔧 chore, ⚙️ setting, 📝 docs, 🐛 fix

#12 Feat/component/ProgressBar/DEVING-28
  package-lock.json
  package.json
  src/app/preview/progress/page.tsx
  src/assets/icon/person.svg
  src/components/ui/Progress.tsx
  tailwind.config.ts
Labels: ✨ feat

#17 Feat/component/badge/DEVING-37
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/preview/tag/page.tsx
  src/components/ui/Tag.tsx
  tailwind.config.ts
Labels: ✨ feat, 🔧 chore, 🐛 fix

#22 Feat/component/tech stack/DEVING-41
  src/app/preview/tech-stack/page.tsx
  src/components/ui/Icon/BaseIcon.tsx
  src/components/ui/Icon/IconData.ts
  src/components/ui/Icon/getPath.ts
  src/components/ui/Icon/iconRegistry.ts
Labels: ✨ feat, 🔧 chore, ✅ test, AI Review

#23 Feat/component/Dropdownfilter/DEVING-43
  src/app/preview/dropdown/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
Labels: ✨ feat, AI Review

#24 Feat/component/card/DEVING-16
  next.config.mjs
  public/thumbnail.jpg
  src/app/layout.tsx
  src/app/preview/card/page.tsx
  src/components/ui/HorizonCard.tsx
  src/components/ui/VerticalCard.tsx
  src/styles/globals.css
Labels: ✨ feat, 🐛 fix, 💄 style, AI Review

#26 Feat/component/review card/DEVING-45
  src/app/preview/progress/page.tsx
  src/app/preview/review/page.tsx
  src/assets/icon/Star.tsx
  src/components/common/review/RatingStars.tsx
  src/components/common/review/ReviewAvgCard.tsx
  src/components/ui/Progress.tsx
Labels: ✨ feat, 🔧 chore, ✅ test, 💄 style, AI Review

#27 dev 브랜치 component 에픽 동기화
  next.config.mjs
  package-lock.json
  package.json
  public/file.svg
  public/globe.svg
  public/next.svg
  public/thumbnail.jpg
  public/vercel.svg
  public/window.svg
  src/app/layout.tsx
  src/app/preview/card/page.tsx
  src/app/preview/dropdown/page.tsx
  src/app/preview/progress/page.tsx
  src/app/preview/review/page.tsx
  src/app/preview/tag/page.tsx
  src/app/preview/tech-stack/page.tsx
  src/assets/icon/Star.tsx
  src/assets/icon/person.svg
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/components/common/review/RatingStars.tsx
  src/components/common/review/ReviewAvgCard.tsx
  src/components/ui/HorizonCard.tsx
  src/components/ui/Icon/BaseIcon.tsx
  src/components/ui/Icon/IconData.ts
  src/components/ui/Icon/getPath.ts
  src/components/ui/Icon/iconRegistry.ts
  src/components/ui/Progress.tsx
  src/components/ui/Tag.tsx
  src/components/ui/VerticalCard.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ feat, 🔧 chore, 🐛 fix, ✅ test, 💄 style

#28 markup 브랜치 dev 동기화
  next.config.mjs
  package-lock.json
  package.json
  public/file.svg
  public/globe.svg
  public/next.svg
  public/thumbnail.jpg
  public/vercel.svg
  public/window.svg
  src/app/layout.tsx
  src/app/preview/card/page.tsx
  src/app/preview/dropdown/page.tsx
  src/app/preview/progress/page.tsx
  src/app/preview/review/page.tsx
  src/app/preview/tag/page.tsx
  src/app/preview/tech-stack/page.tsx
  src/assets/icon/Star.tsx
  src/assets/icon/person.svg
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/components/common/review/RatingStars.tsx
  src/components/common/review/ReviewAvgCard.tsx
  src/components/ui/HorizonCard.tsx
  src/components/ui/Icon/BaseIcon.tsx
  src/components/ui/Icon/IconData.ts
  src/components/ui/Icon/getPath.ts
  src/components/ui/Icon/iconRegistry.ts
  src/components/ui/Progress.tsx
  src/components/ui/Tag.tsx
  src/components/ui/VerticalCard.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ feat, 🔧 chore, 🐛 fix, ✅ test, 💄 style

#20 Feat/markup/login/DEVING-24 로그인 페이지 개발
  .github/workflows/pr-check.yml
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/login/components/DummyUser.tsx
  src/app/login/components/LoginForm.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/common/Header.tsx
  src/hooks/mutations/useUserMutation.ts
  src/hooks/useDebounde.ts
  src/hooks/useLoginForm.ts
  src/hooks/useReactQuery.tsx
  src/lib/axios/authApi.ts
  src/lib/axios/basicApi.ts
  src/lib/axios/defaultConfig.ts
  src/lib/serverActions.ts
  src/service/api/user.ts
  src/styles/globals.css
Labels: ✨ feat, 🔧 chore, ⚙️ setting, 📝 docs, 🐛 fix, AI Review, ♻️ refactor

#31 Feat/markup/DEVING-10 markup 브랜치 dev 동기화
  .github/workflows/pr-check.yml
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/login/components/DummyUser.tsx
  src/app/login/components/LoginForm.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/common/Header.tsx
  src/hooks/mutations/useUserMutation.ts
  src/hooks/useDebounde.ts
  src/hooks/useLoginForm.ts
  src/hooks/useReactQuery.tsx
  src/lib/axios/authApi.ts
  src/lib/axios/basicApi.ts
  src/lib/axios/defaultConfig.ts
  src/lib/serverActions.ts
  src/service/api/user.ts
  src/styles/globals.css
Labels: ✨ feat, 🔧 chore, ⚙️ setting, 🐛 fix, ♻️ refactor

#30 Feat/component/toast/DEVING-20 Toast 구현
  src/app/layout.tsx
  src/app/preview/toast/page.tsx
  src/assets/icon/check_icon.svg
  src/assets/icon/warning_icon.svg
  src/components/common/Toast.tsx
  src/components/common/ToastContext.tsx
Labels: ✨ feat

#32 Markup 브랜치 dev 동기화
  src/app/preview/tech-stack3/page.tsx
  src/components/ui/Icon/IconData.ts
  src/components/ui/tech-stack/TechSelector.tsx
  src/components/ui/tech-stack/tech-stack-components/CategoryTabs.tsx
  src/components/ui/tech-stack/tech-stack-components/SelectedTechButton.tsx
  src/components/ui/tech-stack/tech-stack-components/SelectedTechList.tsx
  src/components/ui/tech-stack/tech-stack-components/TabButton.tsx
  src/components/ui/tech-stack/tech-stack-components/TechButton.tsx
  src/components/ui/tech-stack/tech-stack-components/TechButtonList.tsx
  src/hooks/useTechSelection.ts
  src/types/techStack.ts
  src/util/getIconDetail.ts
Labels: ✨ feat, 🔧 chore, ✅ test, 💄 style

#33 feat(DEVING-51): API엔드포인트 정리
  src/service/api/endpoints.ts
Labels: ✨ feat, AI Review
