Repository MoimService/Moim-FE, pull requests merged in 2025-03, with the labels that each got.

#41 넷틀리파이 자동배포 변경/DEVING-52
  .github/workflows/netlify-deploy.yml
Labels: ✨ feat

#25 Feat/markup/signup/DEVING-25 회원가입 페이지 개발
  src/app/layout.tsx
  src/app/login/components/EmailInput.tsx
  src/app/login/components/LoginForm.tsx
  src/app/login/components/PasswordInput.tsx
  src/app/preview/chip/page.tsx
  src/app/preview/toast/page.tsx
  src/app/signup/components/EmailInput.tsx
  src/app/signup/components/NameInput.tsx
  src/app/signup/components/PasswordCheckInput.tsx
  src/app/signup/components/PasswordInput.tsx
  src/app/signup/components/PositionInput.tsx
  src/app/signup/components/SignupForm.tsx
  src/app/signup/page.tsx
  src/assets/icon/check_icon.svg
  src/assets/icon/warning_icon.svg
  src/components/common/Header.tsx
  src/components/common/PositionSelect.tsx
  src/components/common/Toast.tsx
  src/components/common/ToastContext.tsx
  src/components/ui/Chip.tsx
  src/hooks/mutations/useUserMutation.ts
  src/hooks/useDebounde.ts
  src/hooks/useLoginForm.ts
  src/hooks/useSignupForm.ts
  src/service/api/user.ts
  src/types/auth.ts
  src/util/validation.ts
Labels: ✨ feat, ⚙️ setting, 🐛 fix, AI Review, ♻️ refactor

#35 Feat/markup/meeting list/Deving-48
  next.config.mjs
  public/cat_profile.png
  src/app/meeting/[category]/page.tsx
  src/app/meeting/components/MeetingExtraInfo.tsx
  src/app/meeting/components/MeetingList.tsx
  src/app/meeting/components/NoResultsMeeting.tsx
  src/app/meeting/components/RecommendMeeting.tsx
  src/app/meeting/components/skeleton/MeetingListSkeleton.tsx
  src/app/meeting/components/skeleton/RecommentMeetingSkeleton.tsx
  src/app/not-found.tsx
  src/app/preview/card/page.tsx
  src/components/common/FloatingButtonGroup.tsx
  src/components/common/Header.tsx
  src/components/ui/Button.tsx
  src/components/ui/HorizonCard.tsx
  src/components/ui/Icon/iconRegistry.ts
  src/components/ui/Progress.tsx
  src/components/ui/SearchInput.tsx
  src/components/ui/SkeletonBasic.tsx
  src/components/ui/VerticalCard.tsx
  src/components/ui/tech-stack/TechSelector.tsx
  src/components/ui/tech-stack/tech-stack-components/TechButton.tsx
  src/hooks/common/useInfiniteScroll.ts
  src/hooks/common/useMediaQuery.ts
  src/hooks/mutations/useMeetingMutation.ts
  src/hooks/queries/useMeetingQueries.ts
  src/hooks/useDebounde.ts
  src/service/api/meeting.ts
  src/types/meeting.ts
  src/util/date.ts
  src/util/getIconDetail.ts
  src/util/searchFilter.ts
Labels: ✨ feat, 🐛 fix

#38 Feat/markup/create meeting/DEVING-40 모임생성 및 수정 페이지 구현
  package-lock.json
  src/app/layout.tsx
  src/app/meeting/components/form/MeetingForm.tsx
  src/app/meeting/components/form/form-filed/CategoryField.tsx
  src/app/meeting/components/form/form-filed/DateField.tsx
  src/app/meeting/components/form/form-filed/DescriptionField.tsx
  src/app/meeting/components/form/form-filed/ImageField.tsx
  src/app/meeting/components/form/form-filed/InfoMessage.tsx
  src/app/meeting/components/form/form-filed/LocationField.tsx
  src/app/meeting/components/form/form-filed/MemberLimitField.tsx
  src/app/meeting/components/form/form-filed/PrivacyField.tsx
  src/app/meeting/components/form/form-filed/RequireApprovalField.tsx
  src/app/meeting/components/form/form-filed/SubmitButton.tsx
  src/app/meeting/components/form/form-filed/TechStackField.tsx
  src/app/meeting/components/form/form-filed/TitleField.tsx
  src/app/meeting/components/form/form-filed/index.ts
  src/app/meeting/components/form/validation.ts
  src/app/meeting/constants/meeting-form/meetingConstants.tsx
  src/app/meeting/create-meeting/page.tsx
  src/app/meeting/edit-meeting/[id]/page.tsx
  src/app/page.tsx
  src/components/ui/form/DatePicker.tsx
  src/components/ui/tech-stack/TechSelector.tsx
  src/components/ui/tech-stack/tech-stack-components/CategoryTabs.tsx
  src/components/ui/tech-stack/tech-stack-components/SelectedTechButton.tsx
  src/components/ui/tech-stack/tech-stack-components/TabButton.tsx
  src/components/ui/tech-stack/tech-stack-components/TechButton.tsx
  src/hooks/mutations/useMeetingFormMutation.ts
  src/service/api/meetingForm.ts
  src/types/meetingForm.ts
  src/util/base64.ts
Labels: ✨ feat, 🔧 chore, 🐛 fix, ✅ test, AI Review

#34 Feat/markup/detail/DEVING-47 상세 페이지 구현
  next.config.mjs
  src/app/layout.tsx
  src/app/meeting/[category]/[id]/page.tsx
  src/app/meeting/components/BackButton.tsx
  src/app/meeting/components/CardRightSection.tsx
  src/app/meeting/components/CardWrapper.tsx
  src/app/meeting/components/ContextLabel.tsx
  src/app/meeting/components/MeetingInfo.tsx
  src/app/meeting/components/ReviewInput.tsx
  src/app/meeting/components/ReviewItem.tsx
  src/app/meeting/components/ReviewList.tsx
  src/app/meeting/components/UserInfo.tsx
  src/app/meeting/components/modal-content/ModalBeforeLogin.tsx
  src/app/meeting/components/modal-content/ModalCancel.tsx
  src/app/meeting/components/modal-content/ModalRegisterCheck.tsx
  src/app/meeting/components/modal-content/ModalRegisterComplete.tsx
  src/app/meeting/components/modal-content/ModalRegisterInput.tsx
  src/app/meeting/components/modal-content/ModalRegisterWait.tsx
  src/app/meeting/components/skeletons/SkeletonMeetingInfo.tsx
  src/app/meeting/components/skeletons/SkeletonMeetingTotalInfo.tsx
  src/app/meeting/components/skeletons/SkeletonReviewItem.tsx
  src/app/meeting/components/skeletons/SkeletonReviewList.tsx
  src/app/meeting/components/skeletons/SkeletonUserInfo.tsx
  src/app/preview/gnb/page.tsx
  src/app/preview/progress/page.tsx
  src/assets/icon/Star.tsx
  src/assets/thumbnail.png
  src/components/common/Header.tsx
  src/components/common/review/RatingStarsEdit.tsx
  src/components/common/review/ReviewAvgCard.tsx
  src/components/ui/HorizonCard.tsx
  src/components/ui/SkeletonBasic.tsx
  src/components/ui/tech-stack/tech-stack-components/TechButton.tsx
  src/hooks/common/useInfiniteScroll.ts
  src/hooks/common/useMediaQuery.ts
  src/hooks/mutations/useCommentMutation.ts
  src/hooks/mutations/useMeetingMutation.ts
  src/hooks/mutations/useUserMutation.ts
  src/hooks/queries/useCommentQueries.ts
  src/hooks/queries/useMeetingQueries.ts
  src/hooks/useCard.tsx
  src/hooks/useReactQuery.tsx
  src/lib/serverActions.ts
  src/service/api/comment.ts
  src/service/api/meeting.ts
  src/service/api/user.ts
  src/util/date.ts
  tailwind.config.ts
Labels: ✨ feat, ♻️ refactor

#43 Feat/dev markup 충돌 수정/Deving-53
  next.config.mjs
  public/cat_profile.png
  src/app/meeting/[category]/page.tsx
  src/app/meeting/components/CardWrapper.tsx
  src/app/meeting/components/MeetingExtraInfo.tsx
  src/app/meeting/components/MeetingList.tsx
  src/app/meeting/components/NoResultsMeeting.tsx
  src/app/meeting/components/RecommendMeeting.tsx
  src/app/meeting/components/skeleton/MeetingListSkeleton.tsx
  src/app/meeting/components/skeleton/RecommentMeetingSkeleton.tsx
  src/app/not-found.tsx
  src/app/preview/card/page.tsx
  src/components/common/FloatingButtonGroup.tsx
  src/components/common/Header.tsx
  src/components/ui/Button.tsx
  src/components/ui/HorizonCard.tsx
  src/components/ui/Icon/iconRegistry.ts
  src/components/ui/Progress.tsx
  src/components/ui/SearchInput.tsx
  src/components/ui/VerticalCard.tsx
  src/components/ui/tech-stack/TechSelector.tsx
  src/hooks/common/useMediaQuery.ts
  src/hooks/mutations/useMeetingMutation.ts
  src/hooks/queries/useMeetingQueries.ts
  src/hooks/useDebounde.ts
  src/service/api/meeting.ts
  src/types/meeting.ts
  src/util/getIconDetail.ts
  src/util/searchFilter.ts
Labels: ✨ feat, 🐛 fix, ♻️ refactor

#37 Feat/markup/mypage/DEVING-44 마이페이지
  package-lock.json
  src/app/(user-page)/mypage/MyPageClient.tsx
  src/app/(user-page)/mypage/components/BasicEdit.tsx
  src/app/(user-page)/mypage/components/BasicInfo.tsx
  src/app/(user-page)/mypage/components/ContactEdit.tsx
  src/app/(user-page)/mypage/components/ContactInfo.tsx
  src/app/(user-page)/mypage/components/PasswordEdit.tsx
  src/app/(user-page)/mypage/components/PasswordInfo.tsx
  src/app/(user-page)/mypage/components/ProfileImage.tsx
  src/app/(user-page)/mypage/components/TechStackEdit.tsx
  src/app/(user-page)/mypage/components/TechStackInfo.tsx
  src/app/(user-page)/mypage/components/skeletons/SkeletonBasicInfo.tsx
  src/app/(user-page)/mypage/components/skeletons/SkeletonContactInfo.tsx
  src/app/(user-page)/mypage/components/skeletons/SkeletonPasswordInfo.tsx
  src/app/(user-page)/mypage/components/skeletons/SkeletonProfileImage.tsx
  src/app/(user-page)/mypage/components/skeletons/SkeletonTechStackInfo.tsx
  src/app/(user-page)/mypage/page.tsx
  src/app/login/components/DummyUser.tsx
  src/app/login/page.tsx
  src/app/meeting/constants/meeting-form/meetingConstants.tsx
  src/app/preview/button/page.tsx
  src/app/preview/chip/page.tsx
  src/assets/icon/editLogo.svg
  src/components/common/Dropdown.tsx
  src/components/ui/tech-stack/tech-stack-components/SelectedTechButton.tsx
  src/hooks/queries/useMyPageQueries.ts
  src/hooks/useTechSelection.ts
  src/service/api/mypageProfile.ts
  src/styles/globals.css
  src/types/mypageTypes.ts
  src/util/imageBase64.ts
  tailwind.config.ts
Labels: ✨ feat, 🐛 fix, AI Review, ♻️ refactor

#44 Feat/issue/meeting list infinite scroll/Deving-55
  src/app/meeting/components/MeetingList.tsx
  src/components/common/Header.tsx
  src/hooks/common/useMediaQuery.ts
Labels: ✨ feat

#46 Feat/markup/my meeting i made/DEVING-50
  next.config.mjs
  src/app/(user-page)/components/CardRightSection.tsx
  src/app/(user-page)/components/Created.tsx
  src/app/(user-page)/components/Joined.tsx
  src/app/(user-page)/components/MeetingTypeTab.tsx
  src/app/(user-page)/components/ModalProfile.tsx
  src/app/(user-page)/components/ModalUserList.tsx
  src/app/(user-page)/components/Tab.tsx
  src/app/(user-page)/components/UserItem.tsx
  src/app/(user-page)/my-meeting/comments/page.tsx
  src/app/(user-page)/my-meeting/layout.tsx
  src/app/(user-page)/my-meeting/likes/page.tsx
  src/app/(user-page)/my-meeting/my/page.tsx
  src/app/layout.tsx
  src/app/login/components/DummyUser.tsx
  src/app/preview/modal/Some.tsx
  src/components/common/Description.tsx
  src/components/common/Header.tsx
  src/components/common/NotYet.tsx
  src/components/ui/Button.tsx
  src/components/ui/modal/Modal.tsx
  src/hooks/mutations/useCommentMutation.ts
  src/hooks/mutations/useMyMeetingMutation.ts
  src/hooks/queries/useMyMeetingQueries.ts
  src/hooks/queries/useMyPageQueries.ts
  src/hooks/useCard.tsx
  src/middleware.ts
  src/service/api/meeting.ts
  src/service/api/mymeeting.ts
  src/service/api/mypageProfile.ts
  src/types/meeting.ts
  src/types/myMeeting.ts
Labels: ✨ feat, 🐛 fix

#47 Feat/markup/mypage/DEVING-44
  src/app/(user-page)/mypage/components/BasicEdit.tsx
  src/app/(user-page)/mypage/components/BasicInfo.tsx
  src/app/(user-page)/mypage/components/ContactEdit.tsx
  src/app/(user-page)/mypage/components/PasswordEdit.tsx
  src/app/(user-page)/mypage/components/TechStackEdit.tsx
  src/app/(user-page)/mypage/components/TechStackInfo.tsx
  src/components/common/Header.tsx
  src/components/ui/tech-stack/tech-stack-components/TechButtonList.tsx
Labels: ✨ feat, 🐛 fix, ♻️ refactor

#48 Feat/refactor/meeting list/DEVING-57
  package-lock.json
  src/app/meeting/components/MeetingList.tsx
  src/app/meeting/components/RecommendMeeting.tsx
  src/components/ui/HorizonCard.tsx
  src/components/ui/VerticalCard.tsx
  src/hooks/queries/useMeetingQueries.ts
Labels: ♻️ refactor

#50 Feat/refactor/meeting created/DEVING-59 나의 모임 - 내가 만든 모임 리펙토링
  src/app/(user-page)/my-meeting/_features/CardRightSection.tsx
  src/app/(user-page)/my-meeting/_features/Created.tsx
  src/app/(user-page)/my-meeting/_features/ModalProfile.tsx
  src/app/(user-page)/my-meeting/_features/ModalUserList.tsx
  src/app/(user-page)/my-meeting/_features/PublicDropdown.tsx
  src/app/(user-page)/my-meeting/_features/skeletons/SkeletonMeetingList.tsx
  src/app/(user-page)/my-meeting/_features/skeletons/SkeletonProfile.tsx
  src/components/common/Dropdown.tsx
  src/hooks/mutations/useMyMeetingMutation.ts
  src/service/api/mymeeting.ts
Labels: ✨ feat, 🐛 fix, 💄 style

#55 Feat/refactor/i created prefetch/DEVING-66
  src/app/(user-page)/my-meeting/_features/CardRightSection.tsx
  src/app/(user-page)/my-meeting/_features/ModalUserList.tsx
  src/app/(user-page)/my-meeting/my/page.tsx
  src/hooks/queries/useMyMeetingQueries.ts
Labels: ✨ feat

#52 Feat/markup/mypage/DEVING-44 마이페이지
  src/app/(user-page)/mypage/MyPageClient.tsx
  src/app/(user-page)/mypage/_features/BasicEdit.tsx
  src/app/(user-page)/mypage/_features/BasicInfo.tsx
  src/app/(user-page)/mypage/_features/ContactEdit.tsx
  src/app/(user-page)/mypage/_features/PasswordInfo.tsx
  src/app/(user-page)/mypage/_features/ProfileImage.tsx
  src/app/(user-page)/mypage/_features/TechStackEdit.tsx
  src/app/(user-page)/mypage/page.tsx
  src/components/ui/modal/Modal.tsx
  src/components/ui/tech-stack/tech-stack-components/CategoryTabs.tsx
  src/components/ui/tech-stack/tech-stack-components/TabButton.tsx
  src/components/ui/tech-stack/tech-stack-components/TechButton.tsx
  src/components/ui/tech-stack/tech-stack-components/TechButtonList.tsx
  src/constants/mypage/mypageConstant.tsx
  src/types/mypageTypes.ts
Labels: ✨ feat, 🐛 fix, AI Review, ♻️ refactor

#60 feat(DEVING-73): 로컬 환경에서 https로 열기 위해 server.js 추가
  package.json
  server.js
  src/middleware.ts
  src/service/api/meeting.ts
Labels: ✨ feat

#54 Feat/refactor/create meeting/DEVING-65 모임생성 리펙토링
  src/app/meeting/_features/form/MeetingForm.tsx
  src/hooks/mutations/useMeetingFormMutation.ts
  src/types/meetingForm.ts
Labels: 🔧 chore

#58 Feat/markup/participating meeting/DEVING-69 내가참여하고있는 모임 개발
  src/app/(user-page)/my-meeting/_features/CardRightSection.tsx
  src/app/(user-page)/my-meeting/_features/ModalUserList.tsx
  src/app/(user-page)/my-meeting/_features/Participated.tsx
  src/app/(user-page)/my-meeting/my/page.tsx
  src/hooks/queries/useMyMeetingQueries.ts
  src/service/api/endpoints.ts
  src/service/api/mymeeting.ts
Labels: ✨ feat, 🔧 chore

#56 Feat/refactor/mypage-prefetch/DEVING-68 마이페이지 prefetch
  src/app/(user-page)/my-meeting/my/page.tsx
  src/app/(user-page)/mypage/MyPageClient.tsx
  src/app/(user-page)/mypage/_features/BasicEdit.tsx
  src/app/(user-page)/mypage/_features/ContactEdit.tsx
  src/app/(user-page)/mypage/_features/PasswordEdit.tsx
  src/app/(user-page)/mypage/_features/ProfileImage.tsx
  src/app/(user-page)/mypage/_features/TechStackEdit.tsx
  src/app/(user-page)/mypage/page.tsx
  src/hooks/mutations/useMyPageMutation.tsx
  src/hooks/queries/useMyPageQueries.ts
Labels: ✨ feat, 🐛 fix, ♻️ refactor

#57 Feat/refactor/like optimistic update/DEVING-67
  src/app/meeting/_features/CardWrapper.tsx
  src/app/meeting/_features/MeetingExtraInfo.tsx
  src/app/meeting/_features/MeetingList.tsx
  src/components/common/Dropdown.tsx
  src/components/ui/HorizonCard.tsx
  src/components/ui/VerticalCard.tsx
  src/hooks/common/useLikeHandler.ts
  src/hooks/common/useMediaQuery.ts
  src/hooks/queries/useMeetingQueries.ts
  src/service/api/meeting.ts
Labels: ✨ feat, 🐛 fix, ♻️ refactor

#63 Feat/refactor/refresh token/DEVING-73 refreshToken을 이용한 토큰 재발급
  next.config.mjs
  package.json
  server.js
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
  src/components/common/Header.tsx
  src/hooks/mutations/useMeetingFormMutation.ts
  src/hooks/mutations/useUserMutation.ts
  src/hooks/queries/useMyPageQueries.ts
  src/lib/axios/authApi.ts
  src/lib/axios/axiosInstance.ts
  src/lib/axios/basicApi.ts
  src/lib/axios/defaultConfig.ts
  src/lib/serverActions.ts
  src/service/api/comment.ts
  src/service/api/meeting.ts
  src/service/api/meetingForm.ts
  src/service/api/mymeeting.ts
  src/service/api/mypageProfile.ts
  src/service/api/user.ts
Labels: ✨ feat

#64 feat(DEVING-73): 서버 사이드에서 토큰 사용 위해 엑세스 토큰을 서버 쿠키로 저장 및 사용
  src/app/layout.tsx
  src/app/meeting/[category]/page.tsx
  src/app/meeting/_features/MeetingList.tsx
  src/components/common/Header.tsx
  src/hooks/mutations/useUserMutation.ts
  src/lib/axios/axiosInstance.ts
  src/lib/serverActions.ts
  src/util/searchFilter.ts
Labels: ✨ feat

#61 Feat/refactor/all modal/DEVING-76 내가 참여중인 모임 모달 수정
  src/app/(user-page)/my-meeting/_features/CardRightSection.tsx
  src/app/(user-page)/my-meeting/_features/Created.tsx
  src/app/(user-page)/my-meeting/_features/ModalUserList.tsx
  src/app/(user-page)/my-meeting/layout.tsx
  src/app/(user-page)/my-meeting/my/@modal/(.)user-list/page.tsx
  src/app/meeting/[category]/(modal)/need-login/page.tsx
  src/app/meeting/[category]/@modal/(.)need-login/page.tsx
  src/app/meeting/[category]/@modal/default.tsx
  src/app/meeting/[category]/layout.tsx
  src/components/common/Header.tsx
  src/components/ui/HorizonCard.tsx
  src/components/ui/VerticalCard.tsx
  src/components/ui/modal/ModalPortal.tsx
  src/hooks/mutations/useUserMutation.ts
  src/lib/serverActions.ts
  src/middleware.ts
  src/service/api/user.ts
  src/util/searchFilter.ts
Labels: ✨ feat, 🐛 fix

#67 feat/issue/deploy-site-500/DEVING-83
  src/app/meeting/[category]/page.tsx
Labels: 🐛 fix

#65 Feat/markup/my review/DEVING-70
  src/app/(user-page)/my-meeting/_features/Tab.tsx
  src/app/(user-page)/my-meeting/_features/Writable.tsx
  src/app/(user-page)/my-meeting/_features/Written.tsx
  src/app/(user-page)/my-meeting/comments/page.tsx
  src/app/(user-page)/my-meeting/my/page.tsx
  src/app/meeting/_features/ReviewItem.tsx
  src/constants/mypage/mypageConstant.tsx
  src/hooks/queries/useMyCommentQueries.ts
  src/middleware.ts
  src/service/api/comment.ts
  src/service/api/endpoints.ts
  src/service/api/meeting.ts
  src/service/api/mycomments.ts
  src/types/myComment.ts
Labels: ✨ feat

#69 feat(DEVING-75): GNB 상단에 고정
  src/components/common/Header.tsx
Labels: ✨ feat

#72 Feat/refactor/mypage-refactor/DEVING-71 마이페이지 optimistic update
  package-lock.json
  src/app/(user-page)/mypage/MyPageClient.tsx
  src/app/(user-page)/mypage/_features/BasicEdit.tsx
  src/app/(user-page)/mypage/_features/BasicInfo.tsx
  src/app/(user-page)/mypage/_features/ContactEdit.tsx
  src/app/(user-page)/mypage/_features/ContactInfo.tsx
  src/app/(user-page)/mypage/_features/PasswordEdit.tsx
  src/app/(user-page)/mypage/_features/PasswordInfo.tsx
  src/app/(user-page)/mypage/_features/ProfileImage.tsx
  src/app/(user-page)/mypage/_features/TechStackEdit.tsx
  src/app/(user-page)/mypage/_features/TechStackInfo.tsx
  src/app/(user-page)/mypage/page.tsx
  src/components/common/Header.tsx
  src/constants/mypage/mypageCss.tsx
  src/hooks/mutations/useMyPageMutation.tsx
Labels: ♻️ refactor

#68 Feat/refactor/i participated meeting/DEVING-79 내가 참여하고있는 모임 리펙토링
  src/app/(user-page)/my-meeting/_features/CardRightSection.tsx
  src/app/(user-page)/my-meeting/_features/Joined.tsx
  src/app/(user-page)/my-meeting/_features/LeaveMeetingButton.tsx
  src/app/(user-page)/my-meeting/_features/Likes.tsx
  src/app/(user-page)/my-meeting/_features/Participated.tsx
  src/app/(user-page)/my-meeting/_features/PendingStatusChip.tsx
  src/app/(user-page)/my-meeting/likes/page.tsx
  src/app/(user-page)/my-meeting/my/page.tsx
  src/hooks/mutations/useMyMeetingMutation.ts
  src/hooks/queries/useMyMeetingQueries.ts
  src/service/api/meeting.ts
  src/service/api/mymeeting.ts
  src/types/myMeeting.ts
  tailwind.config.ts
Labels: ✨ feat, 🔧 chore, 💄 style, AI Review

#73 Feat/refactor/meeting list mvp feedback/DEVING-72
  .gitignore
  package.json
  src/app/(user-page)/my-meeting/_features/Writable.tsx
  src/app/(user-page)/my-meeting/_features/Written.tsx
  src/app/(user-page)/my-meeting/comments/page.tsx
  src/app/layout.tsx
  src/app/meeting/_features/MeetingList.tsx
  src/app/meeting/_features/RecommendMeeting.tsx
  src/components/common/ErrorComponent.tsx
  src/components/ui/CardImage.tsx
  src/components/ui/HorizonCard.tsx
  src/components/ui/VerticalCard.tsx
  src/hooks/common/useLikeHandler.ts
  src/types/meeting.ts
  tailwind.config.ts
  tsconfig.json
Labels: ✨ feat, ⚙️ setting

#74 Feat/repactor/create meeting/DEVING-84 모임 수정구현
  src/app/meeting/_features/form/MeetingForm.tsx
  src/app/meeting/_features/form/form-filed/ImageField.tsx
  src/app/meeting/_features/form/form-filed/TechStackField.tsx
  src/app/meeting/edit-meeting/[id]/page.tsx
  src/components/ui/tech-stack/TechSelector.tsx
  src/hooks/mutations/useMeetingFormMutation.ts
  src/hooks/useTechSelection.ts
  src/service/api/endpoints.ts
  src/types/meetingForm.ts
Labels: ✨ feat, 🔧 chore

#71 Feat/markup/landing-page/DEVING-78 랜딩페이지
  next.config.mjs
  package-lock.json
  package.json
  public/deving.svg
  public/github.svg
  public/landingLogo.svg
  public/main.png
  public/notion.svg
  public/section1.png
  public/section2.png
  src/app/(user-page)/mypage/MyPageClient.tsx
  src/app/(user-page)/mypage/page.tsx
  src/app/meeting/_features/skeletons/SkeletonUserInfo.tsx
  src/app/page.tsx
  src/assets/icon/devingLogo.svg
  src/assets/icon/github_icon.svg
  src/assets/icon/landing_logo.svg
  src/assets/icon/medium_check_icon.svg
  src/assets/icon/notion_icon.svg
  src/assets/icon/small_check_Icon.svg
  src/components/common/Header.tsx
  src/components/ui/SkeletonBasic.tsx
  src/types/images.d.ts
Labels: ✨ feat, 🐛 fix

#75 Feat/refactor/mypage-refactor/DEVING-71 마이페이지
  src/app/(user-page)/mypage/MyPageClient.tsx
  src/app/(user-page)/mypage/_features/BasicEdit.tsx
  src/app/(user-page)/mypage/_features/BasicInfo.tsx
  src/app/(user-page)/mypage/_features/ContactEdit.tsx
  src/app/(user-page)/mypage/_features/ContactInfo.tsx
  src/app/(user-page)/mypage/_features/PasswordEdit.tsx
  src/app/(user-page)/mypage/_features/PasswordInfo.tsx
  src/app/(user-page)/mypage/_features/ProfileImage.tsx
  src/app/(user-page)/mypage/_features/TechStackEdit.tsx
  src/app/(user-page)/mypage/_features/TechStackInfo.tsx
Labels: ✨ feat, 🐛 fix

#76 Feat/refactor/refactor UI/DEVING-88 이슈중 간단한 UI 수정
  src/app/login/_features/LoginForm.tsx
  src/components/common/Header.tsx
Labels: 💄 style

#77 Feat/issue/user qa/DEVING-86 자체 QA 반영
  src/app/(user-page)/my-meeting/_features/CardRightSection.tsx
  src/app/(user-page)/my-meeting/_features/Created.tsx
  src/app/(user-page)/my-meeting/_features/Likes.tsx
  src/app/(user-page)/my-meeting/_features/ModalUserList.tsx
  src/app/(user-page)/my-meeting/_features/Participated.tsx
  src/app/(user-page)/my-meeting/_features/Writable.tsx
  src/app/(user-page)/my-meeting/_features/Written.tsx
  src/app/(user-page)/my-meeting/my/@modal/(.)profile/page.tsx
  src/app/(user-page)/my-meeting/my/@modal/page.tsx
  src/app/layout.tsx
  src/app/login/_features/LoginForm.tsx
  src/app/meeting/[category]/@modal/[id]/(.)intro-input/page.tsx
  src/app/meeting/_features/CardRightSection.tsx
  src/app/meeting/_features/ReviewInput.tsx
  src/app/signup/page.tsx
  src/components/common/Header.tsx
  src/components/common/PositionSelect.tsx
  src/components/common/ToastContext.tsx
  src/components/ui/HorizonCard.tsx
  src/components/ui/VerticalCard.tsx
  src/components/ui/modal/ModalPortal.tsx
  src/hooks/mutations/useCommentMutation.ts
  src/hooks/mutations/useMyMeetingMutation.ts
  src/hooks/mutations/useUserMutation.ts
  src/hooks/useSignupForm.ts
  src/service/api/meeting.ts
  src/types/error.ts
  src/util/validation.ts
Labels: ✨ feat, 🐛 fix, 💄 style

#78 Feat/refactor/pending meeting/DEVING-87 Pending 모임 섹션 구현
  src/app/(user-page)/my-meeting/_features/Participated.tsx
  src/app/(user-page)/my-meeting/_features/PendingSection.tsx
  src/app/(user-page)/my-meeting/_features/PendingStatusChip.tsx
  src/app/(user-page)/my-meeting/my/page.tsx
  src/app/meeting/_features/form/MeetingForm.tsx
  src/hooks/mutations/useMyMeetingMutation.ts
  src/hooks/queries/useMyMeetingQueries.ts
  src/service/api/endpoints.ts
  src/service/api/mymeeting.ts
  src/types/myMeeting.ts
  tailwind.config.ts
Labels: ✨ feat, 🔧 chore

#79 Feat/markup/landing-page/DEVING-78
  public/basketball.png
  public/beige_cat.png
  public/front_notebook.png
  public/gray_cat.png
  public/headset.png
  public/heart_notebook.png
  public/read_cat.png
  public/white_cat.png
  public/white_notebook_cat.png
  public/yellow_cat.png
  src/app/page.tsx
  tailwind.config.ts
Labels: ✨ feat, 🐛 fix

#80 Feat/issue/qa issue hanna/DEVING-89
  public/hobby_cat.png
  public/mogakco_cat.png
  public/side-project_cat.png
  src/app/(user-page)/my-meeting/_features/Written.tsx
  src/app/meeting/[category]/page.tsx
  src/app/meeting/_features/MeetingExtraInfo.tsx
  src/app/meeting/_features/MeetingList.tsx
  src/app/meeting/_features/NoResultsMeeting.tsx
  src/app/meeting/_features/RecommendMeeting.tsx
  src/components/ui/VerticalCard.tsx
  src/util/searchFilter.ts
  tailwind.config.ts
Labels: ✨ feat, 🐛 fix

#81 Feat/refactor/self qa/DEVING-90
  src/app/(user-page)/my-meeting/_features/Participated.tsx
  src/app/meeting/[category]/[id]/page.tsx
  src/app/meeting/_features/BackButton.tsx
  src/app/meeting/_features/CardRightSection.tsx
  src/app/meeting/_features/TopSection.tsx
Labels: ✨ feat, 💄 style

#83 Feat/refactor/mypage/DEVING-71
  src/app/(user-page)/mypage/MyPageClient.tsx
  src/app/(user-page)/mypage/_features/BasicEdit.tsx
  src/app/(user-page)/mypage/_features/BasicInfo.tsx
  src/app/(user-page)/mypage/_features/ContactEdit.tsx
  src/app/(user-page)/mypage/_features/ContactInfo.tsx
  src/app/(user-page)/mypage/_features/PasswordEdit.tsx
  src/app/(user-page)/mypage/_features/PasswordInfo.tsx
  src/app/(user-page)/mypage/_features/ProfileImage.tsx
  src/app/(user-page)/mypage/_features/TechStackEdit.tsx
  src/app/(user-page)/mypage/_features/TechStackInfo.tsx
  src/app/(user-page)/mypage/page.tsx
  src/hooks/mutations/useMyPageMutation.tsx
  src/types/mypageTypes.ts
Labels: ♻️ refactor

#85 feat(DEVING-91): 마크다운 1차 (ing....)
  README.md
  image.png
  src/assets/readme-img/detail.png
  src/assets/readme-img/join.png
  src/assets/readme-img/list.png
  src/assets/readme-img/member.png
  src/assets/readme-img/mypage.png
Labels: ✨ feat

#84 feat/markup/landing-page/DEVING-78
  src/app/page.tsx
Labels: ♻️ refactor

#87 Feat/markup/landing-page/DEVING-78
  src/app/(user-page)/mypage/_features/ProfileImage.tsx
  src/components/common/Header.tsx
  src/constants/mypage/mypageConstant.tsx
  src/hooks/mutations/useMyPageMutation.tsx
  src/hooks/mutations/useUserMutation.ts
Labels: AI Review, ♻️ refactor

#88 Feat/markup/landing-page/DEVING-78
  src/app/(user-page)/mypage/_features/ProfileImage.tsx
  src/constants/mypage/mypageConstant.tsx
Labels: ♻️ refactor

#86 feat(DEVING-92): 리드미 4차
  README.md
Labels: ✨ feat
